* After APA 19 Academic Thoughts

** Zhuangzi's metametaphysics

One comment I received was how to understand "use". Jiang suggests that we can understand "use" as the use of language and think that language has nothing to do with representing the world. But I disagree. The use must be the use of things. This is clear when we talk about the nature of wind-blowing.

** Truthmaking and grounding

Eddy has reminded me that he did not share the intuition I have with respect to truthmaking and grounding. Although I was a little surprise--as I thought people would agree with me--I think I should work more on this.

Now here are some new thoughts.

First, I think I should abandon my previous argumentative style.

Second, Eddy thinks that the intuition is stronger if we think about the accuracy of pictures/maps. I think this is a good point and a good argumentative strategy.

Third, here is a new strategy. I show that how different understandings of propositions may change how we think whether truthmaking is grounding. If so, then if we think that the notion of truthmaking is not dependent on how we think of propositions, then the truthmaking should not be understood in terms of grounding.
